version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./.env:/app/.env  # Mount .env file into the container
    ports:
      - "8080:8080"
    environment:
      - ADDRESS=root:@tcp(host.docker.internal:3306)/go_crud?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: go_crud
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  mysql_data:
